### ISSUE TITLE
[ Bug report] TypeError: 'Modifier' object is not iterable

### ISSUE THREAD

**Issue by nzooherd** [klesh/JigsawWM#1]
## Issue: Bug report
*Environment: Windows 11 + Python3.10*
![image](https://user-images.githubusercontent.com/83459211/218907450-367fbbc7-7c1d-4861-a3bf-d35018f0ca8e.png)

**Comment by klesh** [comment]
Thanks for reporting, will look into it

**Comment by klesh** [comment]
Hi, @nzooherd , problem has been fixed by https://github.com/klesh/JigsawWM/commit/1e1bb29f591ec3f8b54389d1f07908fc474b0019

Please reinstall and verify if it works for you, thank you.

**Comment by nzooherd** [comment]
The bug has been fixed, but "tkinter" module can't be found. It may be my problem. Thanks
